resource = PlanetType.create(name: "Resources")
strength = PlanetType.create(name: "Strength")
tech = PlanetType.create(name: "Technology")

#Rina
rina_user = User.create(name: "Rina")
rina_gal = Galaxy.create(name: "Rinaland", user_id: rina_user.id, unallocated: 0)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: rina_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: rina_gal.id)

# Echo
echo_user = User.create(name: "Echo")
echo_gal = Galaxy.create(name: "Echo's Galaxy", user_id: echo_user.id, unallocated: 0)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: echo_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: echo_gal.id)

# Matt
matt_user = User.create(name: "Matt")
matt_gal = Galaxy.create(name: "Matt's Galaxy", user_id: matt_user.id, unallocated: 0)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: matt_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: matt_gal.id)

# Prince
prince_user = User.create(name: "Prince")
prince_gal = Galaxy.create(name: "Prince's Galaxy", user_id: prince_user.id, unallocated: 0)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: strength.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: resource.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: prince_gal.id)
Planet.create(name: "PlanetLove", planet_type_id: tech.id, galaxy_id: prince_gal.id)
